### ISSUE TITLE
На счет пункта про приватные поля родительского класса. 

### ISSUE THREAD

**Issue by Pammer** [ichimax/Java-Interview-Questions#1]
Привет с топджавы.=)
Небольшое уточнение.
Ты отдельно от методов написал про приватные поля:
> при наследовании доступ из методов класса наследника к приватным полям класса-предка напрямую запрещен. Для этого есть геттеры и сеттеры; 
private методы не наследуются, а значит создание метода в классе наследнике с именем аналогичным методу класса предка, но с модификатором доступа private — создаст совершенно новый метод и компилятор не предупредит об этом. Аннотация поможет

И на собесе ,если так сказать , могут возникнуть вопросы - " Так, приватные методы не наследуются, лады. А приватные поля наследуются,что ли? и  просто напрямую доступа к ним нет?"
По JLS:
> Members of a class that are declared private are not inherited by subclasses of that class.

и "аннотация поможет" звучит как незавершенное предложение)
Еще вроде у раннего связывания синоним - "статическое". И вот еще не претендую на правдивость, но с  полиморфизмом  сокрытие(hiding) ж идет, не знаю, стоит ли это отобразить 

> Композицию часть предпочитают наследованию

Очепятка походу, "часто" наверно имелось в виду.
Это все так , размышления.
Мне понравился твой конспект, круто, молодец)

**Comment by ichimax** [comment]
Привет! Спасибо за feedback. 
Сейчас попробую исправить
